# -*- coding: utf-8 -*-
"""Operações_com_Sinais_Discretos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14632o5NZz-gETsyHvPrlmhhtRlQQHLRX
"""

pip install matplotlib

import numpy as np
import matplotlib.pyplot as plt

# Definindo uma sequência original x[n]
n = np.arange(-5, 11)
x = np.array([0, 0, 0, 0, 0, 1, 2, 3, 2, 1, 0, 0, 0, 0, 0, 0])

# 1. Deslocamento Temporal: y[n] = x[n - 3] (Atraso)
n_deslocado = n + 3

# 2. Inversão Temporal: y[n] = x[-n]
n_invertido = -n[::-1]
x_invertido = x[::-1]

# Plotagem das Operações
plt.figure(figsize=(12, 8))

# Sinal Original
plt.subplot(3, 1, 1)
plt.stem(n, x)
plt.title("Sinal Original $x[n]$")
plt.grid(True)

# Sinal Deslocado (Atraso)
plt.subplot(3, 1, 2)
plt.stem(n_deslocado, x)
plt.title("Sinal Deslocado (Atraso): $x[n - 3]$")
plt.xlim(-5, 15)
plt.grid(True)

# Sinal Invertido
plt.subplot(3, 1, 3)
plt.stem(n_invertido, x_invertido)
plt.title("Sinal Invertido (Reflexão): $x[-n]$")
plt.grid(True)

plt.tight_layout()
plt.savefig('operacoes_sinais.png')
plt.show()