# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14632o5NZz-gETsyHvPrlmhhtRlQQHLRX
"""

pip install matplotlib

import numpy as np
import matplotlib.pyplot as plt

n = np.arange(-10, 11)

# Impulso
delta = np.where(n == 0, 1, 0)

# Degrau
u = np.where(n >= 0, 1, 0)

# Exponencial
x = 0.8 ** n

plt.figure(figsize=(8,6))

plt.subplot(3,1,1)
plt.stem(n, delta)
plt.title("Impulso δ[n]")

plt.subplot(3,1,2)
plt.stem(n, u)
plt.title("Degrau u[n]")

plt.subplot(3,1,3)
plt.stem(n, x)
plt.title("Exponencial 0.8ⁿ")

plt.tight_layout()
plt.savefig("../resultados/sinais.png")
plt.show()